episodes = 50000
horizon = 1000
environment = 'KukaGymEnv'
agent_type = 'LSPHierarchicalRL'
replay_buffer_capacity = 1e5
random_sample_num = 1000
agent_update_batch_size = 256
checkpoint_interval = 10
checkpoint = ''
test_interval = 100
test_times = 5
policy_switch_samples = [1.2e6]



[agent]
subpolicy_coupling_layer_num = 2
gamma = 0.99
target_smoothing_rate = 0.01
alpha = 0.2
target_update_interval = 1
critic_hidden_layer_num = 2
critic_hidden_layer_size = 128
learning_rate = 3.0e-4